### PR TITLE
Fixing chrome-sandbox issue

### PR DESCRIPTION
**Pull request by antoniomtz**
Fixed issue `[5318:1204/125628.917656:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that repos/openvino_build_deploy/demos/hide_your_mess_behind_demo/dist/linux-unpacked/chrome-sandbox is owned by root and has mode 4755.`

issue #108

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
I can still see this issue. Fresh Ubuntu 24.10.

**Comment by antoniomtz** [comment]
did you rebuilt the binary with: 
```
npm init -y
npm install
npm run dist
```

If so, I have another approach by using chmod which I can add. Just making sure you still see the issue even after re running those commands.

**Comment by antoniomtz** [comment]
@adrianboguszewski pushed some fixes using chmod. Hope this works.

**Comment by adrianboguszewski** [comment]
I can still see the same problem

**Comment by antoniomtz** [comment]
@adrianboguszewski I did a more in depth investigation and this issue was introduced in Ubuntu 24.04 due to new security features. As of now, there is no an easy/clean fix. The easiest right now is to add **--no-sandbox** to the electron command.

https://github.com/electron/electron/issues/42510#issuecomment-2277476226

Also, when you run the binary apply the no sandbox at the end: ./dist/linux-unpacked/hide-your-mess-behind **--no-sandbox** 

I have also improved the libvips42 bundle by using the existing libraries in side node_modules.

I have tested this on a third computer with fresh Ubuntu 24.04.  Hope it works on your end.

**Comment by antoniomtz** [comment]
Interestingly, after the first time running --no-sandbox, I no longer need to add it. It is a very strange issue. Once you fix it, it goes away for any future build, even deleting dist and node_modules folders and rebuilding the app. That's the reason I couldn't replicate it on my other Ubuntu 24 machine once I "fix" it.

**Review by adrianboguszewski — APPROVED** [review]

**Comment by adrianboguszewski** [comment]
Cool! Thanks, Antonio!

**Pull request merged**
