### PR TITLE
Speedup background removal

### PR DESCRIPTION
**Pull request by vishniakov-nikolai**
What did:
- use RequestAnimationFrame to do not perform extra operations
- Output canvas decreased to 800x600 pixels
- Infer request extracted and reuses between inferences (there are option to use two IR and rotate them)
- opencv-wasm replaced to sharp library, postprocessing optimized
- made attempt to convert model to IR differently (looks like that doesn't have significant effect)

What should do more (not in this PR, these are my suggestions):
- take from canvas and send to backend already resized image 256x256 that fits as model input
- convert original model, change input to int8 precision to do not transform input data
- use int8 weights
- play with compiled model configuration

Addition proposals:
- Avoid global variables usage

### CODE REVIEW

**Comment by raymondlo84** [comment]
wow! more updates!! <3 @adrianboguszewski  =)

**Comment by adrianboguszewski** [comment]
@vishniakov-nikolai @Roszczyk something is wrong with this PR. When I switch to this branch on my Ubuntu, I can no longer run `npm start` without SIGSEGV

**Comment by Roszczyk** [comment]
@adrianboguszewski I believe it should run on OV 2024.3 as well. I'll have a look. 

Before running an application, it's good to check if the modules are up-to-date using npm install.

**Comment by raymondlo84** [comment]
What's the status?

**Comment by Roszczyk** [comment]
@raymondlo84 The only issue here is measurement of inference time. Those two infer requests cause weird results. @vishniakov-nikolai, do you have any idea how to improve it?

**Comment by vishniakov-nikolai** [comment]
I can propose this change (see latest commit). I replaced async inference into synchronous, it makes everything slightly faster.
With async inference, we've found bottleneck and going to improve it, but not earlier that 2025.0

**Comment by Roszczyk** [comment]
@vishniakov-nikolai Great, I'll review it and try to merge with main. Thank you!

**Comment by adrianboguszewski** [comment]
@vishniakov-nikolai this PR needs to be rebased on the current master branch. I already copied some solutions from here to the master branch.

**Comment by adrianboguszewski** [comment]
Closing as nothing is happening here. Please create a new PR, based on the latest master.

**Pull request closed without merging**
