### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raymondlo84**
@adrianboguszewski, what's the default one that works well? Llama3? Shouldn't we include the same instruction as the other healthcare assistant for downloading the model?

### CODE REVIEW

**Comment by raymondlo84** [comment]
Ar... I tried again and it does all the downloading on the main loop. Interesting flow. Let me think what to make his better as the main.py load up shows no progress for a while. A few print statement to show what the machine is doing is always nice.

**Comment by raymondlo84** [comment]
Shouldn't we add a flow to use NPU for whisper? Let us aim for NPU by default, then GPU, then CPU?
```
def load_asr_model(model_name: str) -> None:
    global asr_model, asr_processor

    model_path = MODEL_DIR / model_name

    device = "GPU" if "GPU" in get_available_devices() else "CPU"
```

**Comment by raymondlo84** [comment]
What's the advantage of using AUTO here? 

```
def load_chat_model(model_name: str, token: str = None) -> OpenVINOLLM:
    model_path = MODEL_DIR / model_name

    device = "GPU" if "GPU" in get_available_devices() else "AUTO"
```

**Comment by raymondlo84** [comment]
What can we do the update the layout. Can we do something like all boxes on the left and right side is the chat box? That way we don't have to scroll down and up.

**Comment by raymondlo84** [comment]
Where is the sample pdf file we can use for testing RAG side?

**Comment by riacheruvu** [comment]
@raymondlo84 , I'll add that PDF file and the layout updates. Thanks!

**Comment by riacheruvu** [comment]
> @raymondlo84 , I'll add that PDF file and the layout updates. Thanks!

I created another PR for this (https://github.com/openvinotoolkit/openvino_build_deploy/pull/33) - @adrianboguszewski, would be great to get your thoughts on it!

**Comment by adrianboguszewski** [comment]
All, please check #34

**Comment by adrianboguszewski** [comment]
> Shouldn't we add a flow to use NPU for whisper? Let us aim for NPU by default, then GPU, then CPU?
> 
> ```
> def load_asr_model(model_name: str) -> None:
>     global asr_model, asr_processor
> 
>     model_path = MODEL_DIR / model_name
> 
>     device = "GPU" if "GPU" in get_available_devices() else "CPU"
> ```

Why NPU? Whisper uses dynamic shapes which are not supported.

> What's the advantage of using AUTO here?
> 
> ```
> def load_chat_model(model_name: str, token: str = None) -> OpenVINOLLM:
>     model_path = MODEL_DIR / model_name
> 
>     device = "GPU" if "GPU" in get_available_devices() else "AUTO"
> ```

Just promotion of AUTO device

**Comment by adrianboguszewski** [comment]
Already addressed in #34

**Pull request closed without merging**
